export const projects = [
  { id: '1',
    name: 'SoundlyInvest',
    slug: 'soundlyinvest',
    url: 'https://soundlyinvest.com/',
    imgsrc: '/images/project_soundlyinvest.jpg',
    mobilesrc: '/images/project_soundlyinvest_mobile.jpg',
    github: 'https://github.com/gavinmgrant/soundlyinvest-client',
    description: 'This full-stack web application is a rental property calculator that allows users to save, update, and delete property investment reports.',
    bullets: [ 
      'Implemented a responsive client using JavaScript and React.js library that passes data to components via context and state.',
      'Architected RESTful API endpoints using Node.js/Express routers to perform CRUD operations POST, GET, PATCH, AND DELETE.',
      'Engineered a PostgreSQL database to save reports and user data while seamlessly integrating with the Express application.',
      'Integrated Google Maps Places API with the client to autocomplete property address inputs.',
    ],
    technologies: [
      'HTML5', 
      'CSS', 
      'JavaScript', 
      'React', 
      'Node.js', 
      'Express', 
      'PostgreSQL', 
      'Knex.js', 
      'JWT', 
      'RESTful APIs'
    ]
  },
  { id: '2',
    name: 'Permitful',
    slug: 'permitful',
    url: 'https://permitful.com/',
    imgsrc: '/images/project_permitful.jpg',
    mobilesrc: '/images/project_permitful_mobile.jpg',
    github: 'https://github.com/gavinmgrant/permitful-client',
    description: 'This full-stack web application is a rental property calculator that allows users to save, update, and delete property investment reports.',
    bullets: [ 
      'Implemented a responsive client using JavaScript and React.js library that passes data to components via context and state.',
      'Architected RESTful API endpoints using Node.js/Express routers to perform CRUD operations POST, GET, PATCH, AND DELETE.',
      'Engineered a PostgreSQL database to save reports and user data while seamlessly integrating with the Express application.',
      'Integrated Google Maps Places API with the client to autocomplete property address inputs.',
    ],
    technologies: [
      'HTML5', 
      'CSS', 
      'JavaScript', 
      'React', 
      'Node.js', 
      'Express', 
      'PostgreSQL', 
      'Knex.js', 
      'JWT', 
      'RESTful APIs'
    ]
  },
  { id: '3',
    name: 'Cadre General Contractors',
    slug: 'cadre',
    url: 'https://cadregeneralcontractors.com/',
    imgsrc: '/images/project_cadre.jpg',
    mobilesrc: '/images/project_cadre_mobile.jpg',
    github: null,
    description: 'This is website was designed for Seattle-based general contractor Cadre General Contractors',
    bullets: [ 
      'Integrated the website into the WordPress content management system.',
      'Leveraged the Salient WordPress theme to create a responsive user experience.',
      'Designed with Search Engine Optimization best practices to increase visibility in search engines',
      'Created a dynamic portfolio page to showcase the client\'s projects and expertise.',
    ],
    technologies: [
      'WordPress'
    ]
  },
  { id: '4',
    name: 'Name This City',
    slug: 'name-this-city',
    url: 'https://gavinmgrant.github.io/quiz-app/',
    imgsrc: '/images/project_name-this-city.jpg',
    mobilesrc: '/images/project_name-this-city_mobile.jpg',
    github: 'https://github.com/gavinmgrant/quiz-app',
    description: 'This is an urban geography quiz app that tests your knowledge of cities across the globe.',
    bullets: [ 
      'Developed single-purpose template generation and event handler functions in JavaScript.',
      'Utilized semantic HTML, along with CSS and the jQuery JavaScript library.',
      'Follows a11y best practices and allows full usability via the keyboard.',
      'Implemented a render() function, that conditionally regenerates the view each time the store is updated.',
    ],
    technologies: [
      'HTML5', 
      'CSS', 
      'JavaScript', 
      'jQuery', 
    ]
  },
  { id: '5',
    name: 'Happy Hour Helper',
    slug: 'happy-hour-helper',
    url: 'https://gavinmgrant.github.io/happy-hour-helper/',
    imgsrc: '/images/project_happy-hour-helper.jpg',
    mobilesrc: '/images/project_happy-hour-helper_mobile.jpg',
    github: 'https://github.com/gavinmgrant/happy-hour-helper',
    description: 'This app recommends food and cocktail recipes for users planning a happy hour.',
    bullets: [ 
      'Built a responsive front-end application using JavaScript and the jQuery library.',
      'Utilized JS code separated into single-purpose, reusable, clearly named functions while returning an accessible DOM tree.',
      'Integrated the app with two external APIs that use search parameters and callbacks to retrieve pertinent data.',
      'Designed with accessibility in mind by using a11y best practices in semantic HTML.',
    ],
    technologies: [
      'HTML5', 
      'CSS', 
      'JavaScript', 
      'jQuery',
      'RESTful APIs', 
    ]
  },
]